site_name: MkDocs Bootstrap Theme
site_url: http://mkdocs.github.io/mkdocs-bootstrap/
site_description: MkDocs Bootstrap Theme
site_author: Tom Christie & Dougal Matthews

repo_url: https://github.com/mkdocs/mkdocs-bootstrap

copyright: Copyright &copy; 2014 <a href="https://twitter.com/_tomchristie">Tom Christie</a>, <a href="http://www.dougalmatthews.com/">Dougal Matthews</a>.

theme:
    name: bootstrap

nav:
    - Home: index.md

plugins:
    - search
